package com.constants;

public interface AnimationConstants {
	// PLAYER ANIMATION
	int ANIMATION_TICK=0;
	int ANIMATION_STARTING_INDEX = 0;
	int ANIMATION_TICK_LIMIT = 15;
	
	// ENEMY ANIMATION
	int ENEMY_ANIMATION_TICK=0;
	int ENEMY_ANIMATION_STARTING_INDEX = 0;
	int ENEMY_ANIMATION_TICK_LIMIT = 15;
}
